# Generated by Django 3.0 on 2025-01-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Route')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Route_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair', models.CharField(max_length=100)),
                ('ROUTE_POINT1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='routepoint1', to='myapp.Route_point')),
                ('ROUTE_POINT2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='routepoint2', to='myapp.Route_point')),
            ],
        ),
    ]
