# Generated by Django 3.0 on 2025-01-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default=0, max_length=100)),
                ('longtiude', models.CharField(default=0, max_length=100)),
                ('VEHICLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Vehicle')),
            ],
        ),
    ]
