# Generated by Django 3.0 on 2025-01-17 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_buscheckins'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buscheckins',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 4, 53, 22, 953034)),
        ),
    ]
