# Generated by Django 3.0 on 2025-01-19 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20250117_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscheckins',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 19, 16, 14, 2, 410771)),
        ),
    ]
