# Generated by Django 3.0 on 2025-01-19 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20250119_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscheckins',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 19, 19, 52, 11, 905533)),
        ),
    ]
